language: python
python:
- 2.7
deploy:
  provider: gae
  keyfile: indieweb-test-49d75f4fc415.json
  default: true
  project: indieweb-test
  on: master
before_install:
- openssl aes-256-cbc -K $encrypted_498292065e17_key -iv $encrypted_498292065e17_iv
  -in indieweb-test-49d75f4fc415.json.enc -out indieweb-test-49d75f4fc415.json -d
